export type Project = {
  name: string;
  /** Summary of the project. Reworded here; the repo's own GitHub description differs. */
  description: string;
  /** The reason the project exists, stated in one sentence. */
  why: string;
  href: string;
  lang: string;
  year: string;
  /** Extra facets shown next to language and year. Omit anything already in `lang`. */
  tags: string[];
};

/** Featured work, in display order. Adding a project is one entry. */
export const projects: Project[] = [
  {
    name: "pydsa",
    description:
      "Data structures and algorithms implemented in Python from raw slots upward, from the dynamic array to a graph route planner.",
    why: "Sixteen notebooks, each one depending on the structures built in the one before it.",
    href: "https://github.com/kokko-ng/pydsa",
    lang: "Python",
    year: "2026",
    tags: ["16 notebooks"],
  },
  {
    name: "py8bit",
    description: "A complete 8-bit computer implemented in Python, built to teach computer architecture.",
    why: "Registers, ALU, control unit and assembler, in sequence, until the whole machine fits in your head at once.",
    href: "https://github.com/kokko-ng/py8bit",
    lang: "Python",
    year: "2026",
    tags: ["CPU + assembler"],
  },
  {
    name: "kokko-janitor",
    description:
      "Codebase clean-up for Claude Code: lint fixes run in parallel, and candidate refactorings are judged by an agent.",
    why: "Git worktrees give each agent its own copy of the repository, so a dozen can refactor at once without colliding.",
    href: "https://github.com/kokko-ng/kokko-janitor",
    lang: "Shell",
    year: "2026",
    tags: ["Claude Code"],
  },
  {
    name: "remotion-tutorial",
    description:
      "Narrated technical tutorial videos with Remotion: the voiceover is generated by Azure TTS, and the subtitles are timed to the word.",
    why: "A topic becomes an hour of animated explanation, with subtitles landing on the word rather than the sentence.",
    href: "https://github.com/kokko-ng/remotion-tutorial",
    lang: "TypeScript",
    year: "2026",
    tags: ["Remotion"],
  },
  {
    name: "kokko-devcontainer",
    description: "A development container for macOS, built on Colima, Ghostty, and Claude Code.",
    why: "The environment I work in, specified so that it reproduces on a machine that has never been configured.",
    href: "https://github.com/kokko-ng/kokko-devcontainer",
    lang: "Dockerfile",
    year: "2026",
    tags: ["macOS"],
  },
];
